name: CI Makefile Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  setup:
    name: Setup Python and Install Dependencies
    runs-on: ubuntu-latest

    outputs:
      python-version: ${{ steps.set-python.outputs.python-version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Create virtualenv and install dependencies
        run: make env

      - name: Persist virtualenv
        uses: actions/upload-artifact@v4
        with:
          name: python-venv
          path: .venv
          retention-days: 1

  lint:
    name: Linting with Ruff
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          name: python-venv
          path: .venv

      - name: Lint with ruff
        run: make lint

  format:
    name: Format check
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v4
      with:
        name: python-env
        path: .venv

    - name: Check formatting with black
      run: make format-check

  test:
    name: Tests + Coverage
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v4
      with:
        name: python-env
        path: .venv

    - name: Run tests with coverage
      run: make test-coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: unittests
        name: codecov-iris-classifier-project

